on:
  pull_request:
  push:
   branches:
     - main
jobs:
  build:
    name: Generate wrapper files and build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: HatsuneMiku3939/direnv-action@v1
      - uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.0

      - name: Install all deps
        run: npm run install-opam-npm

      - name: Generate icon wrappers
        run: opam exec dune exec -- generator

      - name: Check that generated code matches VC code
        run: git diff --exit-code

      - name: Build
        run: opam exec dune build

